version: '3.1'

services:

  db:
    image: postgres:13.1
    privileged: true
    ports:
      - "5432:5432"
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 5s
       timeout: 5s
       retries: 5
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: todo

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    command: bash -c
      "
      python manage.py migrate
      && python manage.py loaddata db.json
      && python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
